# Generated by Django 5.0.4 on 2024-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('guitarname', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('fretboardtype', models.CharField(max_length=100)),
                ('bodymaterial', models.CharField(max_length=100)),
                ('pickups', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
